# Generated by Django 3.2.4 on 2021-07-18 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('idcapitulo', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='id de capitulo')),
                ('nomcapitulo', models.CharField(max_length=80, verbose_name='Nombre de capitulo')),
                ('numcapitulo', models.IntegerField(null=True, verbose_name='Numero de capitulo')),
                ('url', models.CharField(max_length=200, verbose_name='Link de video')),
                ('imgcap', models.ImageField(upload_to='capitulo')),
            ],
        ),
        migrations.CreateModel(
            name='Dominio',
            fields=[
                ('iddominio', models.IntegerField(primary_key=True, serialize=False, verbose_name='id de dominio')),
                ('nomdominio', models.CharField(max_length=20, verbose_name='Nombre de dominio')),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('idseccion', models.IntegerField(primary_key=True, serialize=False, verbose_name='id de seccion')),
                ('nomseccion', models.CharField(max_length=20, verbose_name='Nombre de seccion')),
            ],
        ),
        migrations.CreateModel(
            name='Wiki',
            fields=[
                ('idwiki', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Id wiki')),
                ('titulo', models.CharField(max_length=40, verbose_name='Titulo wiki')),
                ('texto', models.TextField(max_length=1000, verbose_name='Texto wiki')),
                ('imagen', models.ImageField(blank=True, upload_to='mapa')),
                ('titulo2', models.CharField(blank=True, max_length=40, verbose_name='Segundo titulo')),
                ('texto2', models.TextField(blank=True, max_length=1000, verbose_name='Texto wiki')),
                ('imagen2', models.ImageField(blank=True, upload_to='mapa2')),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acre.capitulo')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('idcoment', models.AutoField(primary_key=True, serialize=False, verbose_name='Id comentario')),
                ('comentario', models.TextField(max_length=500, verbose_name='Comentario')),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acre.capitulo')),
            ],
        ),
        migrations.AddField(
            model_name='capitulo',
            name='dominio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acre.dominio'),
        ),
        migrations.AddField(
            model_name='capitulo',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acre.seccion'),
        ),
    ]
